# Builds packages/shared/src/grade-plans.ts. Run: python gen_plans.py
import json, re, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
B = os.path.join(HERE, "source")
OUT = os.path.join(HERE, "..", "..", "packages", "shared", "src", "grade-plans.ts")

bach = json.load(open(os.path.join(B, "bachelor.json"), encoding="utf-8"))
mast = json.load(open(os.path.join(B, "master.json"), encoding="utf-8"))
clmg = json.load(open(os.path.join(B, "clmg.json"), encoding="utf-8"))

# B.lab's MSc lists carry notes and typos in course names; show clean names.
RENAME = {
    "Open choice course from Bocconi list": None,  # a free optional
    "1 out of a short list* from Bocconi list:": "Elective from the AI short list",
    "1 course to be chosen": "Course of your choice",
    "1 compulsory course to be chosen from": "Compulsory course of your choice",
    "1 compulsory concentration course": "Concentration course",
    "1 concentration elective on data analysis": "Concentration elective (data analysis)",
    "1 Innovation Specific Elective**": "Innovation elective",
    "National and international institutions law6Politics and policy making":
        "National and international institutions law / Politics and policy making",
    "Behaviourial skills seminars": "Behavioural skills seminars",
    "Seiminari per lo sviluppo di abilità comportamentali": "Seminari per lo sviluppo di abilità comportamentali",
}


def tidy_name(name):
    name = re.sub(r"\s*\(@ Bocconi\)", "", name)
    name = re.sub(r"\s*\(@ Humanitas\)", " · Humanitas", name)
    # Timetable notes: "1st sem.", "2nd sem", "(lessons + exam 1st semester 2nd year)".
    name = re.sub(r"\s*\b\d(st|nd) (sem(ester)?\.?|year)\b\.?", "", name)
    name = re.sub(r"\(\s*\)", "", name)
    name = re.sub(r"module (\d)\(", r"module \1 (", name)
    # "1 corso a scelta tra A / B" → "A / B"; "1 major compulsory course" → "Major compulsory course".
    name = re.sub(r"^1 (corso|insegnamento) a scelta tra ", "", name)
    name = re.sub(r"^1 ([a-z])", lambda m: m.group(1).upper(), name)
    return re.sub(r"\s+", " ", name).strip(" *:")


def number_optionals(rows):
    """Number optional slots in plan order; internships aren't optionals."""
    n = 0
    for r in rows:
        if r["k"] in ("o", "s"):
            n += 1
            r["n"] = f"#{n}"
    return rows


OPT = re.compile(r"(?i)^(elective|opzionale|optional)\b|^1 (free )?elective|elective$|^opzionale n|^electives \(")


def convert(rows, optional_rename=True):
    out = []
    n_opt = 0
    seen = set()
    for r in sorted(rows, key=lambda x: (int(x["anno"] or 0), x["id"])):
        cfu = (r["cfu"] or "").strip()
        if not cfu:
            continue  # extra-curricular / incomplete rows carry no credits
        cfu = float(cfu)
        cfu = int(cfu) if cfu.is_integer() else cfu
        name = re.sub(r"\s+", " ", r["name"]).strip()
        if name in RENAME:
            if RENAME[name] is None:
                name = "Elective"  # matched by OPT below → numbered optional
            else:
                name = RENAME[name]
        name = tidy_name(name)
        year = int(r["anno"] or 1)
        if r["kind"] == "seminar":
            kind = "p"
        elif r.get("isStage"):
            kind = "s"
        elif OPT.search(name):
            kind = "o"
        else:
            kind = "g"
        if kind in ("o", "s") and optional_rename:
            name = "#"  # numbered below; rendered as "Optional N" in the app's language
        key = (name, year, cfu)
        if key in seen and kind == "g":
            continue
        seen.add(key)
        row = {"n": name, "c": cfu, "y": year, "k": kind}
        mod = r.get("module")
        if mod and kind == "g" and mod.lower() != "seminario":
            row["m"] = mod.strip()
        out.append(row)
    return number_optionals(out)


# Bachelor plans come from Bocconi's 2025-26 study-plan guide (pdf_bach.py);
# BEMACC isn't in the guide, so it keeps the B.lab list.
from pdf_bach import plans as pdf
pdf["BEMACC"] = convert(bach["BEMACC"])
pdf["BIG"] = pdf.pop("BIG-PPM")
for rows in pdf.values():
    for r in rows:
        if not r["n"].startswith("#"):
            r["n"] = tidy_name(r["n"])
plans = {
    "bachelor": pdf,
    "master": {k: convert(v) for k, v in mast.items()},
    "clmg": {"CLMG": convert(clmg)},
}

# MSc internships: B.lab lists them as graded rows; at Bocconi they are
# credits without a grade, so they become optional-or-internship slots too.
for rows in plans["master"].values():
    for r in rows:
        if r["k"] == "s":
            r["k"] = "i"
            r["n"] = "Internship"
    number_optionals(rows)

ts = """// Study plans for the grade calculators. GENERATED by
// bocconi-scraper/grade-plans/gen_plans.py — edit that, not this file.
// Bachelor: Bocconi's 2025-26 study-plan guide. MSc and CLMG: the course lists
// B.lab Bocconi publishes for its calculators.
//
// Row: n = course name ("#N" = the Nth optional slot, named in the app's
// language), c = credits, y = year, m = parent course when it is one module of
// an integrated exam, k = kind:
//   g graded course · p pass/fail seminar (no grade, not in the average)
//   o optional course · s optional that an internship can replace
//   i internship (no grade) that an optional course can replace

export type PlanKind = "g" | "p" | "o" | "s" | "i";
export interface PlanRow {
  n: string;
  c: number;
  y: number;
  k: PlanKind;
  m?: string;
}

export const GRADE_PLANS: {
  bachelor: Record<string, PlanRow[]>;
  master: Record<string, PlanRow[]>;
  clmg: Record<string, PlanRow[]>;
} = """ + json.dumps(plans, ensure_ascii=False, indent=1) + ";\n"
open(OUT, "w", encoding="utf-8").write(ts)
for lvl, ps in plans.items():
    for k, rows in ps.items():
        print(lvl, k, len(rows), sum(r["c"] for r in rows), "".join(sorted(r["k"] for r in rows)))
