# Builds packages/shared/src/grade-plans.ts. Run: python gen_plans.py
import json, re, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
B = os.path.join(HERE, "source")
OUT = os.path.join(HERE, "..", "..", "packages", "shared", "src", "grade-plans.ts")

bach = json.load(open(os.path.join(B, "bachelor.json"), encoding="utf-8"))
mast = json.load(open(os.path.join(B, "master.json"), encoding="utf-8"))
clmg = json.load(open(os.path.join(B, "clmg.json"), encoding="utf-8"))

OPT = re.compile(r"(?i)^(elective|opzionale|optional)\b|^1 (free )?elective|elective$|^opzionale n|^electives \(")


def convert(rows, optional_rename=True):
    out = []
    n_opt = 0
    seen = set()
    for r in sorted(rows, key=lambda x: (int(x["anno"] or 0), x["id"])):
        cfu = (r["cfu"] or "").strip()
        if not cfu:
            continue  # extra-curricular / incomplete rows carry no credits
        cfu = float(cfu)
        cfu = int(cfu) if cfu.is_integer() else cfu
        name = re.sub(r"\s+", " ", r["name"]).strip()
        year = int(r["anno"] or 1)
        if r["kind"] == "seminar":
            kind = "p"
        elif r.get("isStage"):
            kind = "s"
        elif OPT.search(name):
            kind = "o"
        else:
            kind = "g"
        if kind in ("o", "s") and optional_rename:
            n_opt += 1
            name = f"#{n_opt}"  # rendered as "Optional N" in the app's language
        key = (name, year, cfu)
        if key in seen and kind == "g":
            continue
        seen.add(key)
        row = {"n": name, "c": cfu, "y": year, "k": kind}
        mod = r.get("module")
        if mod and kind == "g" and mod.lower() != "seminario":
            row["m"] = mod.strip()
        out.append(row)
    return out


# Bachelor plans come from Bocconi's 2025-26 study-plan guide (pdf_bach.py);
# BEMACC isn't in the guide, so it keeps the B.lab list.
from pdf_bach import plans as pdf
pdf["BEMACC"] = convert(bach["BEMACC"])
pdf["BIG"] = pdf.pop("BIG-PPM")
plans = {
    "bachelor": pdf,
    "master": {k: convert(v) for k, v in mast.items()},
    "clmg": {"CLMG": convert(clmg)},
}

# MSc internships: B.lab lists them as graded rows; at Bocconi they are
# credits without a grade, so they become optional-or-internship slots too.
for rows in plans["master"].values():
    for r in rows:
        if r["k"] == "s":
            r["k"] = "i"

ts = """// Study plans for the grade calculators. GENERATED by
// bocconi-scraper/grade-plans/gen_plans.py — edit that, not this file.
// Bachelor: Bocconi's 2025-26 study-plan guide. MSc and CLMG: the course lists
// B.lab Bocconi publishes for its calculators.
//
// Row: n = course name ("#N" = the Nth optional slot, named in the app's
// language), c = credits, y = year, m = parent course when it is one module of
// an integrated exam, k = kind:
//   g graded course · p pass/fail seminar (no grade, not in the average)
//   o optional course · s optional that an internship can replace
//   i internship (no grade) that an optional course can replace

export type PlanKind = "g" | "p" | "o" | "s" | "i";
export interface PlanRow {
  n: string;
  c: number;
  y: number;
  k: PlanKind;
  m?: string;
}

export const GRADE_PLANS: {
  bachelor: Record<string, PlanRow[]>;
  master: Record<string, PlanRow[]>;
  clmg: Record<string, PlanRow[]>;
} = """ + json.dumps(plans, ensure_ascii=False, indent=1) + ";\n"
open(OUT, "w", encoding="utf-8").write(ts)
for lvl, ps in plans.items():
    for k, rows in ps.items():
        print(lvl, k, len(rows), sum(r["c"] for r in rows), "".join(sorted(r["k"] for r in rows)))
