# Builds packages/shared/src/master-admissions-data.ts from the two surveys.
#   python gen.py path/to/Masters-Admission-2026.xlsx
# The xlsx (ASTRA's first-round survey) is not committed: only the admission
# scores derived from it end up in the app. lower-bounds.json is hand-copied
# from B.lab's survey PDF.
import json, os, re, sys
import openpyxl

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "..", "packages", "shared", "src", "master-admissions-data.ts")

# Survey spellings → programme keys.
ALIASES = {
    "AFM": "AFM", "AI": "AI", "CYBER": "CYBER", "DSBA": "DSBA", "ESS": "ESS",
    "EMIT/INTENT": "EMIT", "EMIT": "EMIT", "ACME": "ACME", "GIO": "GIO",
    "FIN": "FIN", "FINANCE": "FIN", "IM CONCENTRATIONS": "IM-CONC", "IM CEMS MIM": "IM-CEMS",
    "CHINA MIM": "CHINA-MIM", "IM DUAL DEGREE ESSEC": "ESSEC", "MM": "MM", "TS": "TS", "PPA": "PPA",
}

def num(v):
    if isinstance(v, (int, float)):
        return float(v)
    if isinstance(v, str):
        m = re.search(r"\d+(?:[.,]\d+)?", v)
        if m:
            return float(m.group(0).replace(",", "."))
    return None

def credits(v):
    n = num(v)
    if n is not None and 60 <= n <= 200:
        return n
    # "Full", "Tutti", "Maximum", "all the exams": a complete second year + a bit.
    if isinstance(v, str) and re.search(r"(?i)full|tutt|max|all|total", v):
        return 120.0
    return None

ws = openpyxl.load_workbook(sys.argv[1], data_only=True).worksheets[0]
scores = {}
skipped = 0
for r in ws.iter_rows(min_row=2, values_only=True):
    gpa, cfu, admitted, master, in_corso = num(r[1]), credits(r[2]), r[4], r[5], r[14]
    key = ALIASES.get(str(master or "").strip().upper())
    if admitted != "Yes" or not key or gpa is None or not 18 <= gpa <= 31 or cfu is None:
        skipped += 1
        continue
    bonus = (1 + 0.05 * max(0, cfu - 90)) if in_corso != "No" else 0  # round 1: 90 credits
    scores.setdefault(key, []).append(round(gpa + bonus * 30 / 110, 2))

bounds = json.load(open(os.path.join(HERE, "lower-bounds.json"), encoding="utf-8"))
data = {
    "survey": {k: sorted(v) for k, v in sorted(scores.items())},
    "lowerBounds": {"round1": bounds["round1"], "round2": bounds["round2"]},
}
ts = """// Master admission survey data. GENERATED by
// bocconi-scraper/master-admissions/gen.py — edit that, not this file.
//   survey       admission scores (out of 30) of students admitted in the first
//                round, from ASTRA's survey, sorted, per programme
//   lowerBounds  lowest admitted score per programme in B.lab's survey
export const MASTER_ADMISSION_DATA: {
  survey: Record<string, number[]>;
  lowerBounds: { round1: Record<string, number>; round2: Record<string, number> };
} = """ + json.dumps(data, indent=1) + ";\n"
open(OUT, "w", encoding="utf-8").write(ts)
print("respondents used:", sum(len(v) for v in scores.values()), "skipped:", skipped)
for k, v in sorted(scores.items()):
    print(f"{k:10} n={len(v):3} min={min(v):.2f} median={v[len(v)//2]:.2f} lb1={bounds['round1'].get(k)}")
