// GENERATED once by bocconi-scraper/grade-plans/gen_legacy_ids.mjs. Do not edit.
// Releases 1.1.0-1.1.3 saved grades under the row's position in the plan ("0", "1", …).
// Rows now have stable ids; this maps the old positions of those plans (as of 1.1.3) to
// them. null = no longer the same course: the grade is dropped and the student is told.
// Safe to delete once nobody can still be on a 1.1.x save (one release after the one that ships it).

export const LEGACY_PLAN_ALIASES: Record<string, Record<string, string>> = {
  "bachelor": {
    "BEMACC": "CLEACC-ENG"
  },
  "master": {
    "DSBA": "DSBA-BA"
  },
  "clmg": {}
};

export const LEGACY_ROW_IDS: Record<string, Record<string, (string | null)[]>> = {
  bachelor: {
    "CLEAM": ["1.economia-aziendale-e-gestione-40109e","1.economia-modulo-1-microeconomia","1.matematica-modulo-1-generale","1.seminario-di-critical-thinking","1.economia-modulo-2-macroeconomia","1.matematica-modulo-2-applicata","1.diritto-modulo-1-privato","1.computer-science","1.english","2.bilancio-modulo-1","2.storia-economica","2.sistema-finanziario","2.statistica","2.diritto-modulo-2-pubblico-comparato","2.bilancio-modulo-2","2.economia-e-management-delle-am-c9303e","2.marketing","2.programmazione-e-controllo","2.seminari-di-business-ethics-e-a11e53","2.lang2","3.finanza-aziendale","3.fondamenti-di-organizzazione","3.strategia-e-innovazione-modulo-d53c54","3.strategia-e-innovazione-modulo-593530","3.seminari-per-lo-sviluppo-delle-d2d567","3.o1","3.diritto-commerciale","3.scienza-delle-finanze","3.o2","3.o3"],
    "CLEF": ["1.economia-aziendale-e-gestione-40109e","1.economia-modulo-1-microeconomia","1.matematica-modulo-1-generale","1.seminario-di-critical-thinking","1.economia-modulo-2-macroeconomia","1.matematica-modulo-2-applicata","1.diritto-modulo-1-privato","1.computer-science","1.english","2.bilancio-modulo-1","2.storia-economica","2.sistema-finanziario","2.statistica","2.diritto-modulo-2-pubblico","2.scienza-delle-finanze","2.bilancio-modulo-2","2.investimenti-finanziari","2.metodi-quantitativi-per-la-finanza","2.seminari-per-lo-sviluppo-delle-d2d567","2.lang2","3.monetary-economics","3.corporate-finance","3.financial-statement-analysis","3.o1","3.diritto-commerciale","3.economia-e-gestione-delle-isti-5bc3bd","3.o2","3.o3"],
    "BESS": ["1.mathematics-module-1-theory-and-methods","1.fundamentals-of-management","1.foundations-of-economics-modul-62f104","1.logic-and-methodology-of-social-sciences","1.mathematics-module-2-applied-mathematics","1.foundations-of-economics-modul-907adb","1.statistics-module-1-theory-and-methods","1.computer-science","1.lang1","2.statistics-module-2-applied-statistics","2.strategic-decision-making-and-markets","2.macroeconomics-and-economic-policy","2.economic-history","2.incentives-design-and-policy","2.private-and-business-law","2.econometrics","2.social-sciences-1-cognitive-sciences","2.lang2","3.empirical-research-methods-and-0fd830","3.social-sciences-2-module-1-org-8d96b8","3.law-and-public-policy","3.o1","3.culture-institutions-and-development","3.social-sciences-2-module-2-sociology","3.international-economics-and-finance","3.o2"],
    "BEMACS": ["1.mathematics-and-statistics-mod-855f95","1.fundamentals-of-computer-science","1.microeconomics","1.principles-of-management","1.mathematics-and-statistics-mod-d83698","1.accounting","1.fundamentals-of-information-te-97f050","1.lang1","2.advanced-mathematics-and-stati-7a34e9","2.advanced-mathematics-and-stati-f1d40c","2.macroeconomics","2.computer-programming","2.technological-innovation-seminars-i","2.european-ip-and-data-law","2.machine-learning","2.econometrics","2.principles-of-finance","2.technological-innovation-seminars-ii","2.lang2","3.big-data-and-databases","3.computational-microeconomics-m-793bf7","3.marketing-analytics","3.o1","3.computational-microeconomics-m-a1cb07","3.information-systems-management","3.o2","3.o3"],
    "BIEM": ["1.economics-module-1-microeconomics","1.management","1.mathematics-module-1-general","1.critical-thinking-seminar","1.introduction-to-the-legal-syst-ed0ee5","1.economics-module-2-macroeconomics","1.mathematics-module-2-applied","1.computer-science","1.lang1","2.financial-accounting-module-1","2.finance-module-1-financial-mar-b4467a","2.statistics","2.economic-history","2.introduction-to-the-legal-syst-382389","2.financial-accounting-module-2","2.finance-module-2-corporate-finance","2.marketing","2.european-economic-policy-public-finance","2.leadership-and-managerial-skills-seminar","2.lang2","3.applications-for-management","3.international-macroeconomics","3.insegnamento-obbligatorio-di-p-b9fe53","3.insegnamento-obbligatorio-di-p-9128ee","3.insegnamento-obbligatorio-di-p-4b02fa","3.csr-ethics-in-business-seminar","3.business-strategy","3.comparative-business-and-european-law","3.o1","3.o2","3.globalization-societies-and-in-22bbb8"],
    "BIEF-ECON": ["1.economics-module-1-microeconomics","1.management","1.mathematics-module-1-general","1.critical-thinking-seminar","1.introduction-to-the-legal-syst-ed0ee5","1.economics-module-2-macroeconomics","1.mathematics-module-2-applied","1.computer-science","1.lang1","2.financial-accounting-module-1","2.finance-module-1-financial-mar-b4467a","2.economic-history","2.statistics","2.introduction-to-the-legal-syst-382389","2.leadership-and-managerial-skills-seminar","2.finance-module-2-corporate-finance","2.financial-accounting-module-2","2.lang2","2.markets-organization-and-incentives","2.international-economics","3.csr-ethics-in-business-seminar","3.comparative-business-and-european-law","3.o1","3.o2","3.globalization-societies-and-in-22bbb8","3.empirical-methods-for-economic-c224b8","3.macroeconomics-and-the-world-economy","3.major-course-1","3.major-course-2","3.major-course-3","3.major-course-4"],
    "BIEF-FIN": ["1.economics-module-1-microeconomics","1.management","1.mathematics-module-1-general","1.critical-thinking-seminar","1.introduction-to-the-legal-syst-ed0ee5","1.economics-module-2-macroeconomics","1.mathematics-module-2-applied","1.computer-science","1.lang1","2.financial-accounting-module-1","2.finance-module-1-financial-mar-b4467a","2.economic-history","2.statistics","2.introduction-to-the-legal-syst-382389","2.leadership-and-managerial-skills-seminar","2.finance-module-2-corporate-finance","2.financial-accounting-module-2","2.lang2","2.international-and-monetary-economics","2.financial-economics","3.csr-ethics-in-business-seminar","3.comparative-business-and-european-law","3.o1","3.o2","3.globalization-societies-and-in-22bbb8","3.empirical-methods-for-finance-a03497","3.business-strategy","3.major-course-1","3.major-course-2","3.major-course-3","3.major-course-4"],
    "CLEACC-ENG": ["1.management-of-cultural-compani-70b14e","1.philosophy-of-art","1.mathematics","1.law-module-1-private-law","1.economics-module-1-microeconomics","1.economic-history-and-history-o-774772","1.critical-approaches-to-the-arts","1.computer-science","1.lang1","2.economics-module-2-macroeconomics","2.statistics","2.critical-approaches-to-the-art-ed586d","2.financial-accounting-module-1","2.cultural-anthropology","2.financial-accounting-module-2","2.fundamentals-of-organization","2.critical-approaches-to-the-art-699aac","2.law-module-2-comparative-public-law","2.leadership-and-managerial-skills-seminar","2.lang2","3.business-planning-and-control","3.advanced-management-modulo-1-c-5f5b31","3.advanced-management-modulo-2-m-391632","3.management-of-public-and-not-f-e5a05c","3.company-and-business-law","3.o1","3.public-finance","3.finance-module-1-corporate-finance","3.finance-module-2-financial-mar-5d5318"],
    "CLEACC": ["1.economia-aziendale-e-delle-ist-93cebf","1.estetica","1.matematica-generale-e-finanziaria","1.diritto-modulo-1-privato","1.economia-modulo-1-microeconomia","1.storia-economica-e-del-pensier-102678","1.metodo-critica-e-ricerca-nelle-946e5a","1.computer-science","1.english","2.economia-modulo-2-macroeconomia","2.statistica","2.metodo-critica-e-ricerca-nelle-d3b140","2.bilancio-modulo-1","2.antropologia-culturale-e-dello-sviluppo","2.bilancio-modulo-2","2.fondamenti-di-organizzazione","2.metodo-critica-e-ricerca-nelle-d3c533","2.diritto-modulo-2-pubblico-comparato","2.seminari-per-lo-sviluppo-delle-d2d567","2.lang2","3.programmazione-e-controllo","3.advanced-management-modulo-1-c-5f5b31","3.advanced-management-modulo-2-m-62223e","3.management-of-public-and-not-f-e5a05c","3.diritto-commerciale","3.o1","3.scienza-delle-finanze","3.finanza-modulo-1-finanza-aziendale","3.finanza-modulo-2-sistema-finanziario"],
    "BIG-DSO": ["1.economics-module-i-consumer-be-920d9c","1.comparative-public-law-and-regulation","1.politics-public-sector","1.quantitative-methods-for-socia-d5cb3e","1.coding-and-data-visualization-in-python","1.economics-module-ii-macro-econ-4ee0d9","1.global-history-and-affairs","1.machine-learning-module-i-introduction","1.quantitative-methods-for-socia-57a877","1.lang1","2.governance-of-digital-technolo-0ca240","2.social-transformations","2.social-media-democracy","2.machine-learning-module-ii-deep-learning","3.climate-change-and-sustainability-hec","2.business-analytics-data-modelling-hec","2.european-governance-hec","2.behavioral-and-cognitive-science-hec","2.introduction-to-ethics-and-phi-d2dd56","2.lang2","3.o1","3.introduction-to-research-metho-f9a4e3","3.entrepreneurial-management-met-198301","3.o2","3.o3","3.o4","3.o5","3.o6","3.o7","3.capstone-project","3.progetto-sul-campo-laboratori"],
    "BAI": ["1.foundations-of-economic-sciences","1.computer-science-module-1-intr-7fd996","1.mathematical-analysis-i-module-1","1.algebra-and-geometry","1.foundations-of-physics-i","1.computer-science-module-2-comp-bbbf99","1.probability","1.mathematical-analysis-i-module-2","2.foundations-of-physics-ii","2.decision-theory-and-human-behaviour","2.mathematical-statistics","2.mathematical-analysis-ii-module-1","2.advanced-programming-and-optim-141b16","2.mathematical-modelling-in-mach-5e0720","2.mathematical-analysis-ii-module-2","2.digital-ethics-seminar","2.behavioural-skills-seminar","2.ai-lab","2.lang","3.game-theory-and-mechanism-design","3.mathematical-modelling-for-finance","3.stochastic-processes-and-simul-8c2b56","3.o1","3.statistical-and-quantum-physics","3.machine-learning-and-artificia-330785","3.mathematical-modelling-for-neuroscience","3.o2"],
    "BGL-GL": ["1.general-jurisprudence","1.critical-thinking-seminar","1.introduction-to-private-law-mo-7da0c0","1.introduction-to-private-law-mo-ec1a4f","1.transnational-constitutional-l-8e0316","1.transnational-constitutional-l-71d52e","1.historical-foundations-of-law-dbe327","1.historical-foundations-of-law-a89a08","2.european-union-law","2.management-of-international-or-d25c22","2.labour-and-social-law","2.international-law","2.legal-tech","2.global-administrative-law","2.microeconomics-or-public-finance","2.criminal-law","2.lang","3.quantitative-analysis-for-global-jurists","3.business-and-corporate-law","3.global-civil-justice-or-crimin-365917","3.economic-analysis-of-law-or-in-b40291","3.administrative-environmental-l-789120","3.regulatory-law-or-global-finance","3.fundamentals-of-it-and-ip-law-51b5d4","3.legal-clinic-or-internship","3.due-seminari-tra-cultural-aspe-c4b955"],
    "BGL-DL": ["1.general-jurisprudence","1.critical-thinking-seminar","1.introduction-to-private-law-mo-7da0c0","1.introduction-to-private-law-mo-ec1a4f","1.transnational-constitutional-l-8e0316","1.transnational-constitutional-l-71d52e","1.historical-foundations-of-law-dbe327","1.historical-foundations-of-law-a89a08","2.european-union-law","2.management-of-international-or-d25c22","2.labour-and-social-law","2.international-law","2.legal-tech","2.global-administrative-law","2.microeconomics-or-public-finance","2.criminal-law","2.lang","3.quantitative-analysis-for-global-jurists","3.business-and-corporate-law","3.criminal-procedure","3.disciplina-giuridica-di-bilancio","3.casi-e-questioni-di-diritto-so-fcfa36","3.regulatory-law-or-global-finance","3.accounting-and-financial-state-705f90","3.diritto-privato","3.diritto-tributario"],
    "BEMACC": ["1.management-of-cultural-compani-70b14e","1.mathematics","1.philosophy-of-art","1.law-module-1-private-law","1.economics-module-1-microeconomics","1.critical-approaches-to-the-arts","1.economic-history-and-history-o-774772","1.computer-science","1.lang1","2.economics-module-2-macroeconomics","2.statistics","2.critical-approaches-to-the-art-ed586d","2.financial-accounting-module-1","2.cultural-anthropology","2.financial-accounting-module-2","2.fundamentals-of-organization","2.critical-approaches-to-the-art-699aac","2.law-module-2-comparative-public-law","2.lang2","2.leadership-and-managerial-skills-seminar","3.business-planning-and-control","3.management-of-public-and-not-f-e5a05c","3.advanced-management-modulo-1-c-5f5b31","3.advanced-management-modulo-2-m-391632","3.company-and-business-law","3.finance-module-1-corporate-finance","3.finance-module-2-financial-mar-5d5318","3.public-finance","3.o1"],
    "BIG": ["1.political-science-and-comparat-927f26","1.quantitative-methods-for-socia-ae786d","1.law-module-1-comparative-public-law","1.introduction-to-economics-modu-7129ac","1.introduction-to-economics-modu-9e7b24","1.political-philosophy","1.quantitative-methods-for-socia-a64bec","1.marketing-research-skills-for-1703c6","1.computer-science","1.lang1","2.management-of-government-organizations","2.international-relations","2.public-economics","2.history-module-1-global-history","2.negotiation-skills","2.policy-evaluation","2.economics-and-politics-of-the-3429d8","2.law-module-2-international-and-613d96","2.political-economics","2.lang2","3.sociology","3.public-governance","3.o1","3.o2","3.history-module-2-history-of-po-4d8539","3.media-political-elites-and-the-public","3.o3","3.o4"],
  },
  master: {
    "CRSG": ["1.emerging-topics-in-cybersecurity","1.software-methodologies-and-arc-af8c17","1.software-methodologies-and-arc-acd816","1.artificial-intelligence-for-security","1.cyber-risk-and-data-protection-law","1.introduction-to-cyber-risk","1.technology-risk-governance","1.methods-and-data-analytics-for-0d08f7","1.cyber-security-technologies-pr-4c6828","1.institutional-scenarios-of-cyber-risk","1.strategy-and-governance-for-cyber-risk","2.o1","2.behavioural-skills-seminar","2.o2","2.lang","2.o3",null,"2.ethics-seminar","2.o4"],
    "AI": ["1.ai-ethics-seminar","1.information-theory","1.algorithms-for-optimization-an-1213e8","1.machine-learning-lab","1.computer-vision-and-image-processing","1.deep-learning-and-reinforcement-learning","1.software-engineering","1.language-technology","1.mathematical-methods-in-comput-63fea0",null,"2.o1","2.o2","2.o3","2.lang","2.o4","2.o5"],
    "GIO": ["1.economics-and-policy-of-global-markets","1.quantitative-methods-for-social-sciences","1.policy-analysis-and-evaluation","1.national-and-international-ins-6e3d78","1.strategic-and-hr-management-in-34cac7","1.politics-and-policy-making","1.government-and-international-o-9ccfef","1.business-government-relations-38bb49","1.public-accounting-and-performa-45d80c",null,"2.professional-english-seminars","2.o1","2.o2",null,"2.lang2","2.o3","2.o4"],
    "IM-GLOBAL": ["1.performance-evaluation-and-measurement","1.global-scenarios-module-2-geop-5844b2","1.principles-of-business-analytics","1.seminar-on-collaborative-competences","1.global-scenarios-module-1-macroeconomics","1.international-finance-challenge","1.managing-organizations","1.international-finance","1.marketing-analytics","1.comparative-corporate-law","1.global-strategy","2.o1","2.o2","2.global-operations-and-supply-c-dc3180","2.o3","2.professional-english-seminars","2.lang2"],
    "FINANCE": ["1.empirical-finance","1.theory-of-finance","1.financial-data-science","1.financial-institutions-and-markets-law","1.financial-reporting-and-analysis-lab","1.risk-management-and-value-in-b-4236d3","1.corporate-finance-business-valuation","1.investment-banking","1.quantitative-finance-and-deriv-6027f6","1.behavioural-skills-seminars","1.quantitative-finance-and-deriv-09d146","2.professional-english-seminars","2.o1","2.o2","2.lang2","2.o3","2.o4"],
    "IM": ["1.global-strategy","1.global-scenarios-module-2-macroeconomics","1.global-operations-and-supply-c-dc3180","1.performance-measurement","1.marketing-analytics","1.international-finance","1.global-scenarios-module-1-geop-28f2e7","1.international-comparative-business-law","1.managing-organizations","1.principles-of-business-analytics","2.lang2","2.o1","2.o2","2.o3"],
    "DAAIHS": ["1.data-systems-in-healthcare","1.privacy-ethics-and-regulations-46b5cc","1.machine-learning","1.advanced-computer-programming","1.artificial-intelligence-module-2","1.biology-and-genetics-humanitas","1.data-science-for-clinics-humanitas","1.clinical-epidemiology-humanitas","1.artificial-intelligence-module-1","1.advanced-statistics-for-health-sciences","1.o1","2.o1",null,"2.applications-of-artificial-int-91f188","2.guidelines-for-quality-assessm-bd36a6","2.foreign-language-humanitas","2.next-generation-sequencing-and-2a824b"],
    "DSBA": ["1.behavioural-skills-seminar","1.business-analytics","1.computer-programming-and-datab-6c3b3f","1.natural-language-processing","1.statistics-and-probability","1.machine-learning","1.econometrics-for-big-data","2.o1","2.digital-privacy-seminar",null,"2.o2","2.lang"],
    "MM": ["1.market-research-and-business-forecasting","1.understanding-consumer-consume-e0d265","1.industry-analysis-industrial-e-ec18bb","1.brand-management","1.understanding-consumer-consume-d780b2","1.channel-marketing-trade-evolut-711629","1.legal-issues-in-marketing","1.strategic-marketing-and-analyt-a0e193","1.behavioural-skills-seminars","1.innovation-in-the-data-economy","1.strategic-marketing-and-analyt-f02e23","2.o1","2.o2",null,"2.professional-english-seminars","2.o3",null,"2.lang2","2.o4"],
    "IM-CONCENTRATION": ["1.law-course-of-your-choice-labo-42e68c","1.corporate-strategy","1.marketing-management-advanced","1.business-game","1.advanced-corporate-finance-for-5a3a34","1.performance-measurement","1.behavioural-skills-seminars","1.economy-and-society-module-1","1.economy-and-society-module-2","1.principles-of-business-analytics","1.human-resources-management","2.o1","2.lang2","2.o2","2.concentration-course","2.professional-english-seminars","2.concentration-elective-data-analysis"],
    "AFM": ["1.corporate-reporting-module-1-c-af9346","1.fair-value-accounting-reportin-f7b890","1.macroeconomic-trends-for-busin-5cb07d","1.behavioural-skills-seminars","1.corporate-reporting-module-2-n-f3e2c0","1.performance-measurement-and-co-f20c8e","1.data-analysis-for-business-decisions","1.business-law-or-global-corpora-7abf05","1.financial-management-and-finan-c6ab32","1.corporate-governance","2.o1","2.professional-english-seminars","2.o2","2.o3",null,null,"2.lang2","2.o4"],
    "CLELI": ["1.tassazione-delle-societa-e-dei-gruppi","1.modelli-finanziari-per-la-valutazione","1.finanza-strategica","1.analisi-strategiche-e-valutazi-9d9ab4","1.sistemni-di-corporate-governance","1.principi-contabili-internazionali","1.seminari-per-lo-sviluppo-di-ab-6cf50f","1.bilancio-e-operazioni-di-gesti-f7c7b4","1.diritto-commerciale-corso-progredito","2.o1","2.o2","2.lang2","2.o3","2.professional-english-seminars","2.diritto-dei-mercati-e-degli-st-db8e3f"],
    "ESS": ["1.advanced-statistics-for-econom-c08852","1.econometrics","1.foundations-of-social-sciences-f49d32","1.o1","1.competition-law-and-practice","1.o2","1.behavioural-skills-seminars","1.advanced-mathematics-for-econo-7a6dd1","1.o3","1.advanced-microeconomics-or-adv-da6884","2.o1",null,"2.o2",null,"2.o3","2.o4","2.professional-english-seminars","2.lang2"],
    "PPA": ["1.population-dynamics-and-policies","1.political-science-module-2-int-62c78f","1.political-science-module-1-top-a8ecd6","1.methods-and-tools-for-policy-analysis","1.behavioral-skills-seminar","1.public-administration","1.public-economics","1.economics-and-politics","1.decisions-and-organizations","1.law-and-policy-making","2.o1","2.o2","2.lang2","2.o3","2.o4"],
    "TS": ["1.sustainable-finance-and-esg-investing","1.behavioural-skills-and-leaders-0111cf","1.materials-towards-circular-economy","1.designing-sustainable-cities","1.impact-and-sustainability-measurement","1.innovation-for-sustainability","1.technologies-for-energy-and-su-61fdf5","1.sustainability-policy-decision-68707a","1.management-and-economics-for-s-5859c0","1.technologies-for-energy-and-su-70a45a","1.esg-law","1.management-and-economics-for-s-5e19c4","2.business-and-marketing-plan-workshop","2.data-analytics-for-sustainability","2.o1","2.sustainable-operations-supply-290b6c","2.lang","2.sustainable-entrepreneurship-workshop","2.diversity-and-global-policy-te-3ddc38"],
    "ACME": ["1.applied-research-in-cultural-i-ac6cfa","1.applied-research-in-cultural-i-e671f6","1.behavioural-skills-seminars","1.cultural-mediation","1.majors-workshop-1","1.project-and-team-management","1.performance-measurement","1.management-of-cultural-industr-5fe5fa","1.management-of-cultural-industr-ed4bef","1.european-and-international-adv-ec9ebe","1.majors-workshop-2","2.professional-english-seminars","2.majors-workshop-3","2.o1",null,"2.majors-workshop-4","2.o2",null,"2.lang2"],
    "EMIT": ["1.data-analytics-and-visualization","1.technology-and-innovation-strategy","1.business-economics-ii-analytic-methods","1.business-economics-i-empirical-methods","1.strategic-decision-making","1.behavioural-skills-seminars","1.venture-capital-and-valuation","1.major-compulsory-course","1.intellectual-property-and-comp-a5942a","1.fundamentals-of-innovation-and-060c32","2.o1",null,null,"2.o2","2.o3","2.professional-english-seminars","2.lang2","2.o4"],
  },
  clmg: {
    "CLMG": ["1.istituzioni-di-diritto-privato-modulo-1","1.filosofia-del-diritto","1.english","1.diritto-costituzionale-italian-0cddc2","1.principi-di-economia-a-scelta-f7d7b7","1.critical-thinking","1.istituzioni-di-diritto-privato-modulo-2","1.diritto-romano-modulo-1","1.quantitative-methods","2.economia-aziendale-e-bilancio-modulo-1","2.management-and-accounting-modu-dec1c9","2.diritto-commerciale","2.legal-argumentation-and-econom-cd50d8","2.informatica-per-giurisprudenza","2.legal-english","2.diritto-comparato-a-scelta-pri-355d44","2.roman-law-module-2-roman-found-071492","2.history-of-law-module-1-introd-92f0d5","2.storia-del-diritto-modulo-2","3.diritto-contabile-e-fiscale-modulo-1","3.diritto-penale","3.diritto-processuale-civile-modulo-2","3.lang2","3.diritto-processuale-penale","3.diritto-contabile-e-fiscale-modulo-2","3.eu-law","3.diritto-del-lavoro","3.diritto-processuale-civile-modulo-1","4.diritto-del-lavoro-corso-progr-2db55a","4.diritto-amministrativo-a-scelt-1b8f5d","4.diritto-civile-a-scelta-fra-co-ce3970","4.international-law","4.diritto-commerciale-corso-prog-2676a0","4.diritto-processuale-penale-cor-ec8639","4.diritto-costituzionale-corso-p-883f64","4.diritto-penale-corso-progredit-b65702","5.diritto-amministrativo-corso-p-2b7ad7","5.seminari-moot-cliniche-legali-d60d6f","5.diritto-civile-corso-progredit-c64bd2","5.o1","5.o2","5.computing-ai-and-the-law","5.o3"],
  },
};
